//! Utility functions for the SDK

/// debug print queries generated by diesel for the postgres backend
///
/// # Example
///
/// ```rust
/// use diesel::prelude::*;
///
/// diesel::table! {
///     use diesel::sql_types::*;
///
///     user (id) {
///         id -> int8,
///         name -> Text,
///     }
/// }
///
/// let conn = ft_sdk::default_pg().unwrap();
///
/// let query = user::table
///     .select(user::name)
///     .filter(user::id.eq(9))
///     .limit(1);
///
/// dbg_query(&query);
/// ```
pub fn dbg_query<T: diesel::query_builder::QueryFragment<diesel::pg::Pg>>(query: &T) {
    #[cfg(feature = "debug")]
    ft_sdk::println!("{:?}", diesel::debug_query::<diesel::pg::Pg, _>(query));
}
