/// debug print queries generated by diesel
/// TODO: add a crate feature to conditionally enable this
pub(crate) fn dbg_query<T: diesel::query_builder::QueryFragment<diesel::pg::Pg>>(query: &T) {
    dbg!(diesel::debug_query::<diesel::pg::Pg, _>(query));
}
